import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="text-red-300 min-h-screen min-w-full bg-gray-20 ">
      {children}
    </div>
  );
}
